# Generated by Django 5.2.14 on 2026-05-27 05:43

import apps.common.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[apps.common.validators.validate_phone])),
                ('mobile_no', models.CharField(blank=True, max_length=20, validators=[apps.common.validators.validate_phone])),
                ('address', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Parties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('role', models.CharField(choices=[('vendor', 'Vendor'), ('customer', 'Customer'), ('broker', 'Broker'), ('transporter', 'Transporter'), ('manufacturer', 'Manufacturer')], db_index=True, max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='parties.party')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role'],
            },
        ),
        migrations.CreateModel(
            name='PartyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('document_type', models.CharField(choices=[('gst_certificate', 'GST Certificate'), ('pan_card', 'PAN Card'), ('cancelled_cheque', 'Cancelled Cheque'), ('agreement', 'Agreement'), ('msme', 'MSME Certificate'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='party_documents/%Y/%m/')),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('party_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='parties.partyrole')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('customer_segment', models.CharField(blank=True, max_length=100)),
                ('billing_preference', models.CharField(blank=True, max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('party_role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to='parties.partyrole')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('mobile_no', models.CharField(max_length=20, validators=[apps.common.validators.validate_phone])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('party_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='parties.partyrole')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommercialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit_days', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('party_role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_profile', to='parties.partyrole')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrokerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('license_no', models.CharField(blank=True, max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('party_role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='broker_profile', to='parties.partyrole')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('bank_name', models.CharField(max_length=150)),
                ('branch_name', models.CharField(blank=True, max_length=150)),
                ('account_no', models.CharField(db_index=True, max_length=30)),
                ('ifsc_code', models.CharField(max_length=11, validators=[apps.common.validators.validate_ifsc])),
                ('micr_no', models.CharField(blank=True, max_length=15)),
                ('account_holder_name', models.CharField(max_length=150)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('party_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='parties.partyrole')),
            ],
            options={
                'verbose_name_plural': 'Bank Details',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StatutoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('cin_no', models.CharField(blank=True, max_length=21)),
                ('pan_no', models.CharField(blank=True, max_length=10, validators=[apps.common.validators.validate_pan])),
                ('tan_no', models.CharField(blank=True, max_length=10)),
                ('msme_no', models.CharField(blank=True, max_length=50)),
                ('esi_no', models.CharField(blank=True, max_length=50)),
                ('pf_no', models.CharField(blank=True, max_length=50)),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='statutory/pan/')),
                ('msme_certificate', models.FileField(blank=True, null=True, upload_to='statutory/msme/')),
                ('other_document', models.FileField(blank=True, null=True, upload_to='statutory/other/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('party_role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statutory_detail', to='parties.partyrole')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['name', 'is_active'], name='parties_par_name_f2cbc4_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['code'], name='parties_par_code_73330d_idx'),
        ),
        migrations.AddIndex(
            model_name='partyrole',
            index=models.Index(fields=['party', 'role', 'is_active'], name='parties_par_party_i_5c2a70_idx'),
        ),
        migrations.AddConstraint(
            model_name='partyrole',
            constraint=models.UniqueConstraint(fields=('party', 'role'), name='unique_party_role_per_party'),
        ),
        migrations.AddConstraint(
            model_name='bankdetail',
            constraint=models.UniqueConstraint(fields=('party_role', 'account_no'), name='unique_bank_account_per_role'),
        ),
    ]
