# Generated by Django 5.2.14 on 2026-05-27 08:10

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='mobile_no',
            field=models.CharField(max_length=20, validators=[apps.common.validators.validate_mobile]),
        ),
        migrations.AlterField(
            model_name='party',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='party',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='statutorydetail',
            name='cin_no',
            field=models.CharField(blank=True, max_length=21, verbose_name='CIN No'),
        ),
        migrations.AlterField(
            model_name='statutorydetail',
            name='esi_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='ESI No'),
        ),
        migrations.AlterField(
            model_name='statutorydetail',
            name='msme_certificate',
            field=models.FileField(blank=True, null=True, upload_to='statutory/msme/', verbose_name='MSME Certificate'),
        ),
        migrations.AlterField(
            model_name='statutorydetail',
            name='msme_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='MSME No'),
        ),
        migrations.AlterField(
            model_name='statutorydetail',
            name='other_document',
            field=models.FileField(blank=True, null=True, upload_to='statutory/other/', verbose_name='Other Document'),
        ),
        migrations.AlterField(
            model_name='statutorydetail',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='statutory/pan/', verbose_name='PAN Card'),
        ),
        migrations.AlterField(
            model_name='statutorydetail',
            name='pan_no',
            field=models.CharField(blank=True, max_length=10, validators=[apps.common.validators.validate_pan], verbose_name='PAN No'),
        ),
        migrations.AlterField(
            model_name='statutorydetail',
            name='pf_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='PF No'),
        ),
        migrations.AlterField(
            model_name='statutorydetail',
            name='tan_no',
            field=models.CharField(blank=True, max_length=10, verbose_name='TAN No'),
        ),
    ]
