# Generated by Django 5.2.14 on 2026-05-27 05:43

import apps.common.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('company_name', models.CharField(max_length=255)),
                ('vendor_type', models.CharField(choices=[('registered', 'Registered'), ('unregistered', 'Unregistered'), ('composite', 'Composite')], default='registered', max_length=20)),
                ('office_status', models.CharField(choices=[('head_office', 'Head Office'), ('branch', 'Branch')], default='head_office', max_length=20)),
                ('gst_no', models.CharField(blank=True, max_length=15, validators=[apps.common.validators.validate_gst])),
                ('dispatch_location', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('party_role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to='parties.partyrole')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vendor_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='masters.vendorcategory')),
                ('vendor_sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='masters.vendorsubcategory')),
            ],
            options={
                'indexes': [models.Index(fields=['company_name'], name='vendors_ven_company_bf1baf_idx'), models.Index(fields=['gst_no'], name='vendors_ven_gst_no_e6274b_idx')],
            },
        ),
    ]
