# Generated by Django 5.2.14 on 2026-05-27 08:10

import apps.common.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_vendor_types(apps, schema_editor):
    VendorType = apps.get_model('masters', 'VendorType')
    defaults = [
        ('registered', 'Registered'),
        ('unregistered', 'Unregistered'),
        ('composite', 'Composite'),
    ]
    for code, name in defaults:
        VendorType.objects.get_or_create(code=code, defaults={'name': name})


def migrate_vendor_type_fk(apps, schema_editor):
    VendorProfile = apps.get_model('vendors', 'VendorProfile')
    VendorType = apps.get_model('masters', 'VendorType')
    for profile in VendorProfile.objects.all():
        old_code = profile.vendor_type_old
        if not old_code:
            continue
        vendor_type = VendorType.objects.filter(code=old_code).first()
        if vendor_type:
            profile.vendor_type_id = vendor_type.id
            profile.save(update_fields=['vendor_type_id'])


def normalize_office_status(apps, schema_editor):
    VendorProfile = apps.get_model('vendors', 'VendorProfile')
    VendorProfile.objects.exclude(
        office_status__in=['active', 'inactive']
    ).update(office_status='active')


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('masters', '0002_alter_vendorcategory_options_vendortype'),
        ('parties', '0002_alter_contactperson_mobile_no_alter_party_mobile_no_and_more'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(seed_vendor_types, migrations.RunPython.noop),
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='vendor_type',
            new_name='vendor_type_old',
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='vendor_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='vendors',
                to='masters.vendortype',
            ),
        ),
        migrations.RunPython(migrate_vendor_type_fk, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='vendor_type_old',
        ),
        migrations.RunPython(normalize_office_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='vendorprofile',
            name='office_status',
            field=models.CharField(
                choices=[('active', 'Active'), ('inactive', 'Inactive')],
                default='active',
                max_length=20,
                verbose_name='Office Status',
            ),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='gst_no',
            field=models.CharField(
                blank=True,
                max_length=15,
                validators=[apps.common.validators.validate_gst],
                verbose_name='GST No',
            ),
        ),
    ]
